services:
  reverse-proxy:
    image: "traefik:v2.5"
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./certs:/etc/certs:ro
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./config/static.yml:/etc/traefik/traefik.yml:ro
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=false"
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external: true
