services:
  reverse-proxy:
    image: "traefik:v2.5"
    ports:
      - "80:80"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=false"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
